### ISSUE TITLE
Crash with invalid URL

### ISSUE THREAD

**Issue by PhilHannent** [ewsjs/xhr#2]
Good morning,

During testing I have found that if the Exchange server URL is invalid and xhr is used then we get a crash which I am not able to trap inline:

```
[app.js] Root errorError: Invalid message signature: Basic Realm=""
[app.js] Root error stackError: Invalid message signature: Basic Realm=""
    at decodeType2Message (/Users/administrator/dev/room-booking-api/node_modules/ntlm-client/lib/ntlm.js:85:9)
    at Request._callback (/Users/administrator/dev/room-booking-api/node_modules/@ewsjs/xhr/src/ntlmProvider.js:78:36)
    at Request.self.callback (/Users/administrator/dev/room-booking-api/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/Users/administrator/dev/room-booking-api/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/Users/administrator/dev/room-booking-api/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at /Users/administrator/dev/room-booking-api/node_modules/async-listener/glue.js:188:31
    at process._tickCallback (internal/process/next_tick.js:63:19)
{"message":"[app.js] Root errorError: Invalid message signature: Basic Realm=\"\"","level":"error"}
{"message":"[app.js] Root error stackError: Invalid message signature: Basic Realm=\"\"\n    at decodeType2Message (/Users/administrator/dev/room-booking-api/node_modules/ntlm-client/lib/ntlm.js:85:9)\n    at Request._callback (/Users/administrator/dev/room-booking-api/node_modules/@ewsjs/xhr/src/ntlmProvider.js:78:36)\n    at Request.self.callback (/Users/administrator/dev/room-booking-api/node_modules/request/request.js:185:22)\n    at Request.emit (events.js:182:13)\n    at Request.<anonymous> (/Users/administrator/dev/room-booking-api/node_modules/request/request.js:1161:10)\n    at Request.emit (events.js:182:13)\n    at IncomingMessage.<anonymous> (/Users/administrator/dev/room-booking-api/node_modules/request/request.js:1083:12)\n    at Object.onceWrapper (events.js:273:13)\n    at IncomingMessage.emit (events.js:187:15)\n    at endReadableNT (_stream_readable.js:1094:12)\n    at /Users/administrator/dev/room-booking-api/node_modules/async-listener/glue.js:188:31\n    at process._tickCallback (internal/process/next_tick.js:63:19)","level":"error"}
```

I am using:
@ewsjs/xhr v1.3.1
ews-javascript-api v0.9.4

**Comment by PhilHannent** [comment]
Hi,

I just found the fix is already in a pull request:

https://github.com/gautamsi/node-ntlm-client/pull/1/commits/6f9e13f98886c29154523cfe05976328b8b4a3d4

It would be cool if you could merge that.

Thanks
Phil

**Comment by gautamsi** [comment]
merged.
