### ISSUE TITLE
Crash in Url which does not return the www-authenticate header

### ISSUE THREAD

**Issue by PhilHannent** [ewsjs/xhr#4]
Hi,

When we set our Url to something unexpected ( https://office365.com ) we get an application crash:

```
[iis.js] Root errorError: www-authenticate not found on response of second request
[iis.js] Root error stackError: www-authenticate not found on response of second request
   at Request._callback (C:\Git\roombookingapi\node_modules\@ewsjs\xhr\src\ntlmProvider.js:75:31)
   at Request.self.callback (C:\Git\roombookingapi\node_modules\request\request.js:185:22)
   at Request.emit (events.js:182:13)
   at Request.<anonymous> (C:\Git\roombookingapi\node_modules\request\request.js:1161:10)
   at Request.emit (events.js:182:13)
   at IncomingMessage.<anonymous> (C:\Git\roombookingapi\node_modules\request\request.js:1083:12)
   at Object.onceWrapper (events.js:273:13)
   at IncomingMessage.emit (events.js:187:15)
   at endReadableNT (_stream_readable.js:1094:12)
   at C:\Git\roombookingapi\node_modules\async-listener\glue.js:188:31
   at process._tickCallback (internal/process/next_tick.js:63:19)
{"message":"[iis.js] Root errorError: www-authenticate not found on response of second request","level":"error"}
{"message":"[iis.js] Root error stackError: www-authenticate not found on response of second request\n    at Request._callback (C:\\Git\\roombookingapi\\node_modules\\@ewsjs\\xhr\\src\\ntlmProvider.js:75:31)\n    at Request.self.callback (C:\\Git\\roombookingapi\\node_modules\\request\\request.js:185:22)\n    at Request.emit (events.js:182:13)\n    at Request.<anonymous> (C:\\Git\\roombookingapi\\node_modules\\request\\request.js:1161:10)\n    at Request.emit (events.js:182:13)\n    at IncomingMessage.<anonymous> (C:\\Git\\roombookingapi\\node_modules\\request\\request.js:1083:12)\n    at Object.onceWrapper (events.js:273:13)\n    at IncomingMessage.emit (events.js:187:15)\n    at endReadableNT (_stream_readable.js:1094:12)\n    at C:\\Git\\roombookingapi\\node_modules\\async-listener\\glue.js:188:31\n    at process._tickCallback (internal/process/next_tick.js:63:19)","level":"error"}
```

It would be nicer if the this line were to reject with the error rather than throw a new:
https://github.com/ewsjs/xhr/blob/master/src/ntlmProvider.ts#L89

It works if we fudge that line to be:

```
if (!response.headers['www-authenticate']) {
    return reject({
        response: 'www-authenticate not found on response of second request'
    });
}
```

**Comment by gautamsi** [comment]
this is fixed now. 
v 1.32 published with thanks to @zmathew
